language: cpp

# What branches are we reacting upon.
branches:
    only:
    - /^master$/
    - /^pre-release$/

# Downloading ccache's cache is around 6s, uploading is around 3s.
cache: ccache

compiler:
- gcc

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-6

install:
- "[ $CC = gcc ] && export CC=gcc-6 || true"
- "[ $CXX = g++ ] && export CXX=g++-6 || true"


script:
- mkdir -p build && cd build && cmake .. && make && make test


notifications:
  email:
    on_success: never
    on_failure: never
  slack:
    secure: "sSVMQUzdW/EI7wuu2TThGI+Pr1CE03yNuY5EG0a1fJ8jz3pURnTNFz1Y/rkwLebKkySNotECb/wOfd31LvdSvrHi+XXeajgA8oyNrmQoCJtWQ5jdWI94hOzWZIlGPPtBqCHQoMYKTmSLg2Fk/Oc+scE31quOEY1F9xgnQvbek3fNKuZdY3cAa9marERfQHz4s2dEuTXk917DJa424MNa9bozvoYfGLobxUzOSJKcL0mDFmBXH4cTljk53/+1huAvn73o57PvmfKNdGCbgQsSg7k/8eSYhEkS6O77LdQLp4YD5huRZgByRiltuegDtncoyGjQ/aIYyVGei/m+dHpQ5cfITn1ipDK5bDQNkIaCnL0rnAg+iOuYFtKQl7TC0pLygZd4roT11m5Z+yLlpcOiPSCszxin9E5feRYPJrLdocz1/ib9ZwwQoZ3yZbl17HmVfDWUuGFZyqfnY/eV4YFlr6mMBi+5e04px9ydzbUH6tTryk/vQN8YMBDNAEClJ/AAJxIXPKHTv2YMfghg45Dcuoxzu3iiN/cqCzE++Jnz7pqIKZcTY/xBFIeiTb4Xnv2JxNMdF/RQ8jaOyKx7XHu8LUCbdvnW9fxIcpKQwfViS/XF2wXPfS/hPwVRohTV0s5Eo7ltcnAjV8Tkh0oN7Nh00Mw14En/81vjF4hst8La4+8="

